// Based of middle C (0 = Last Staff Line)
// const middleC = 23;
// const trebleIndex = -3;
// const altoIndex = 3;
// const bassIndex = 9;

export const keys = [{
  "note": "A0",
  "trebleIndex": -26,
  "bassIndex": -14,
  "altoIndex": -20
}, {
  "note": "A#0",
  "trebleIndex": -26,
  "bassIndex": -14,
  "altoIndex": -20
}, {
  "note": "B0",
  "trebleIndex": -25,
  "bassIndex": -13,
  "altoIndex": -19
}, {
  "note": "C1",
  "trebleIndex": -24,
  "bassIndex": -12,
  "altoIndex": -18
}, {
  "note": "C#1",
  "trebleIndex": -24,
  "bassIndex": -12,
  "altoIndex": -18
}, {
  "note": "D1",
  "trebleIndex": -23,
  "bassIndex": -11,
  "altoIndex": -17
}, {
  "note": "D#1",
  "trebleIndex": -23,
  "bassIndex": -11,
  "altoIndex": -17
}, {
  "note": "E1",
  "trebleIndex": -22,
  "bassIndex": -10,
  "altoIndex": -16
}, {
  "note": "F1",
  "trebleIndex": -21,
  "bassIndex": -9,
  "altoIndex": -15
}, {
  "note": "F#1",
  "trebleIndex": -21,
  "bassIndex": -9,
  "altoIndex": -15
}, {
  "note": "G1",
  "trebleIndex": -20,
  "bassIndex": -8,
  "altoIndex": -14
}, {
  "note": "G#1",
  "trebleIndex": -20,
  "bassIndex": -8,
  "altoIndex": -14
}, {
  "note": "A1",
  "trebleIndex": -19,
  "bassIndex": -7,
  "altoIndex": -13
}, {
  "note": "A#1",
  "trebleIndex": -19,
  "bassIndex": -7,
  "altoIndex": -13
}, {
  "note": "B1",
  "trebleIndex": -18,
  "bassIndex": -6,
  "altoIndex": -12
}, {
  "note": "C2",
  "trebleIndex": -17,
  "bassIndex": -5,
  "altoIndex": -11
}, {
  "note": "C#2",
  "trebleIndex": -17,
  "bassIndex": -5,
  "altoIndex": -11
}, {
  "note": "D2",
  "trebleIndex": -16,
  "bassIndex": -4,
  "altoIndex": -10
}, {
  "note": "D#2",
  "trebleIndex": -16,
  "bassIndex": -4,
  "altoIndex": -10
}, {
  "note": "E2",
  "trebleIndex": -15,
  "bassIndex": -3,
  "altoIndex": -9
}, {
  "note": "F2",
  "trebleIndex": -14,
  "bassIndex": -2,
  "altoIndex": -8
}, {
  "note": "F#2",
  "trebleIndex": -14,
  "bassIndex": -2,
  "altoIndex": -8
}, {
  "note": "G2",
  "trebleIndex": -13,
  "bassIndex": -1,
  "altoIndex": -7
}, {
  "note": "G#2",
  "trebleIndex": -13,
  "bassIndex": -1,
  "altoIndex": -7
}, {
  "note": "A2",
  "trebleIndex": -12,
  "bassIndex": 0,
  "altoIndex": -6
}, {
  "note": "A#2",
  "trebleIndex": -12,
  "bassIndex": 0,
  "altoIndex": -6
}, {
  "note": "B2",
  "trebleIndex": -11,
  "bassIndex": 1,
  "altoIndex": -5
}, {
  "note": "C3",
  "trebleIndex": -10,
  "bassIndex": 2,
  "altoIndex": -4
}, {
  "note": "C#3",
  "trebleIndex": -10,
  "bassIndex": 2,
  "altoIndex": -4
}, {
  "note": "D3",
  "trebleIndex": -9,
  "bassIndex": 3,
  "altoIndex": -3
}, {
  "note": "D#3",
  "trebleIndex": -9,
  "bassIndex": 3,
  "altoIndex": -3
}, {
  "note": "E3",
  "trebleIndex": -8,
  "bassIndex": 4,
  "altoIndex": -2
}, {
  "note": "F3",
  "trebleIndex": -7,
  "bassIndex": 5,
  "altoIndex": -1
}, {
  "note": "F#3",
  "trebleIndex": -7,
  "bassIndex": 5,
  "altoIndex": -1
}, {
  "note": "G3",
  "trebleIndex": -6,
  "bassIndex": 6,
  "altoIndex": 0
}, {
  "note": "G#3",
  "trebleIndex": -6,
  "bassIndex": 6,
  "altoIndex": 0
}, {
  "note": "A3",
  "trebleIndex": -5,
  "bassIndex": 7,
  "altoIndex": 1
}, {
  "note": "A#3",
  "trebleIndex": -5,
  "bassIndex": 7,
  "altoIndex": 1
}, {
  "note": "B3",
  "trebleIndex": -4,
  "bassIndex": 8,
  "altoIndex": 2
}, {
  "note": "C4",
  "trebleIndex": -3,
  "bassIndex": 9,
  "altoIndex": 3
}, {
  "note": "C#4",
  "trebleIndex": -3,
  "bassIndex": 9,
  "altoIndex": 3
}, {
  "note": "D4",
  "trebleIndex": -2,
  "bassIndex": 10,
  "altoIndex": 4
}, {
  "note": "D#4",
  "trebleIndex": -2,
  "bassIndex": 10,
  "altoIndex": 4
}, {
  "note": "E4",
  "trebleIndex": -1,
  "bassIndex": 11,
  "altoIndex": 5
}, {
  "note": "F4",
  "trebleIndex": 0,
  "bassIndex": 12,
  "altoIndex": 6
}, {
  "note": "F#4",
  "trebleIndex": 0,
  "bassIndex": 12,
  "altoIndex": 6
}, {
  "note": "G4",
  "trebleIndex": 1,
  "bassIndex": 13,
  "altoIndex": 7
}, {
  "note": "G#4",
  "trebleIndex": 1,
  "bassIndex": 13,
  "altoIndex": 7
}, {
  "note": "A4",
  "trebleIndex": 2,
  "bassIndex": 14,
  "altoIndex": 8
}, {
  "note": "A#4",
  "trebleIndex": 2,
  "bassIndex": 14,
  "altoIndex": 8
}, {
  "note": "B4",
  "trebleIndex": 3,
  "bassIndex": 15,
  "altoIndex": 9
}, {
  "note": "C5",
  "trebleIndex": 4,
  "bassIndex": 16,
  "altoIndex": 10
}, {
  "note": "C#5",
  "trebleIndex": 4,
  "bassIndex": 16,
  "altoIndex": 10
}, {
  "note": "D5",
  "trebleIndex": 5,
  "bassIndex": 17,
  "altoIndex": 11
}, {
  "note": "D#5",
  "trebleIndex": 5,
  "bassIndex": 17,
  "altoIndex": 11
}, {
  "note": "E5",
  "trebleIndex": 6,
  "bassIndex": 18,
  "altoIndex": 12
}, {
  "note": "F5",
  "trebleIndex": 7,
  "bassIndex": 19,
  "altoIndex": 13
}, {
  "note": "F#5",
  "trebleIndex": 7,
  "bassIndex": 19,
  "altoIndex": 13
}, {
  "note": "G5",
  "trebleIndex": 8,
  "bassIndex": 20,
  "altoIndex": 14
}, {
  "note": "G#5",
  "trebleIndex": 8,
  "bassIndex": 20,
  "altoIndex": 14
}, {
  "note": "A5",
  "trebleIndex": 9,
  "bassIndex": 21,
  "altoIndex": 15
}, {
  "note": "A#5",
  "trebleIndex": 9,
  "bassIndex": 21,
  "altoIndex": 15
}, {
  "note": "B5",
  "trebleIndex": 10,
  "bassIndex": 22,
  "altoIndex": 16
}, {
  "note": "C6",
  "trebleIndex": 11,
  "bassIndex": 23,
  "altoIndex": 17
}, {
  "note": "C#6",
  "trebleIndex": 11,
  "bassIndex": 23,
  "altoIndex": 17
}, {
  "note": "D6",
  "trebleIndex": 12,
  "bassIndex": 24,
  "altoIndex": 18
}, {
  "note": "D#6",
  "trebleIndex": 12,
  "bassIndex": 24,
  "altoIndex": 18
}, {
  "note": "E6",
  "trebleIndex": 13,
  "bassIndex": 25,
  "altoIndex": 19
}, {
  "note": "F6",
  "trebleIndex": 14,
  "bassIndex": 26,
  "altoIndex": 20
}, {
  "note": "F#6",
  "trebleIndex": 14,
  "bassIndex": 26,
  "altoIndex": 20
}, {
  "note": "G6",
  "trebleIndex": 15,
  "bassIndex": 27,
  "altoIndex": 21
}, {
  "note": "G#6",
  "trebleIndex": 15,
  "bassIndex": 27,
  "altoIndex": 21
}, {
  "note": "A6",
  "trebleIndex": 16,
  "bassIndex": 28,
  "altoIndex": 22
}, {
  "note": "A#6",
  "trebleIndex": 16,
  "bassIndex": 28,
  "altoIndex": 22
}, {
  "note": "B6",
  "trebleIndex": 17,
  "bassIndex": 29,
  "altoIndex": 23
}, {
  "note": "C7",
  "trebleIndex": 18,
  "bassIndex": 30,
  "altoIndex": 24
}, {
  "note": "C#7",
  "trebleIndex": 18,
  "bassIndex": 30,
  "altoIndex": 24
}, {
  "note": "D7",
  "trebleIndex": 19,
  "bassIndex": 31,
  "altoIndex": 25
}, {
  "note": "D#7",
  "trebleIndex": 19,
  "bassIndex": 31,
  "altoIndex": 25
}, {
  "note": "E7",
  "trebleIndex": 20,
  "bassIndex": 32,
  "altoIndex": 26
}, {
  "note": "F7",
  "trebleIndex": 21,
  "bassIndex": 33,
  "altoIndex": 27
}, {
  "note": "F#7",
  "trebleIndex": 21,
  "bassIndex": 33,
  "altoIndex": 27
}, {
  "note": "G7",
  "trebleIndex": 22,
  "bassIndex": 34,
  "altoIndex": 28
}, {
  "note": "G#7",
  "trebleIndex": 22,
  "bassIndex": 34,
  "altoIndex": 28
}, {
  "note": "A7",
  "trebleIndex": 23,
  "bassIndex": 35,
  "altoIndex": 29
}, {
  "note": "A#7",
  "trebleIndex": 23,
  "bassIndex": 35,
  "altoIndex": 29
}, {
  "note": "B7",
  "trebleIndex": 24,
  "bassIndex": 36,
  "altoIndex": 30
}, {
  "note": "C8",
  "trebleIndex": 25,
  "bassIndex": 37,
  "altoIndex": 31
}];

export const mappedKeys = keys.reduce(function (map, obj, i) {
  map[obj.note] = {
    ...obj,
    index: i,
  };
  return map;
}, {});